contentitemexportablefields:
  contentitemfields:
    fromServerVersion: 5.0.0
    itemVersion: 2.0.4
    packID: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: Detonate file through active integrations that support file detonation
id: 671d1b8c-8aa2-4400-8774-2606728ebb5c
inputs:
- description: Entry ID of file to be detonated
  key: EntryID
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: EntryID
      root: File
- description: File object of file to be detonated
  key: File
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: File
name: Detonate File - Generic_copy
outputs:
- contextPath: Joe.Analysis.Status
  description: Analysis Status
  type: string
- contextPath: Joe.Analysis.WebID
  description: Web ID
  type: string
- contextPath: File.Name
  description: The file's name (only in case of report type=json)
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file
  type: string
- contextPath: File.Size
  description: File size (only in case of report type=json)
  type: number
- contextPath: File.Type
  description: File type e.g. "PE" (only in case of report type=json)
  type: string
- contextPath: File.Malicious
  description: The File malicious description
  type: unknown
- contextPath: File.Malicious.Description
  description: For malicious files, the reason for the vendor to make the decision
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: DBotScore
  description: The Indicator's object
  type: unknown
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: IP.Address
  description: IP's relevant to the sample
  type: string
- contextPath: DBotScore.Malicious.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Malicious.Detections
  description: The sub analysis detection statuses
  type: string
- contextPath: DBotScore.Malicious.SHA1
  description: The SHA1 of the file
  type: string
- contextPath: Sample.State
  description: The sample state
- contextPath: Sample.ID
  description: The sample ID
- contextPath: File
  description: The File's object
  type: unknown
- contextPath: File.MD5
  description: MD5 hash of the file
  type: string
- contextPath: Joe.Analysis.SampleName
  description: Sample Data, could be a file name or URL
  type: string
- contextPath: Joe.Analysis.Comments
  description: Analysis Comments
  type: string
- contextPath: Joe.Analysis.Time
  description: Submitted Time
  type: date
- contextPath: Joe.Analysis.Runs
  description: Sub-Analysis Information
  type: unknown
- contextPath: Joe.Analysis.Result
  description: Analysis Results
  type: string
- contextPath: Joe.Analysis.Errors
  description: Raised errors during sampling
  type: unknown
- contextPath: Joe.Analysis.Systems
  description: Analysis OS
  type: unknown
- contextPath: Joe.Analysis.MD5
  description: MD5 of analysis sample
  type: string
- contextPath: Joe.Analysis.SHA1
  description: SHA1 of analysis sample
  type: string
- contextPath: Joe.Analysis.SHA256
  description: SHA256 of analysis sample
  type: string
- contextPath: InfoFile.Name
  description: FileName of the report file
  type: string
- contextPath: InfoFile.EntryID
  description: The EntryID of the report file
  type: string
- contextPath: InfoFile.Size
  description: File Size
  type: number
- contextPath: InfoFile.Type
  description: File type e.g. "PE"
  type: string
- contextPath: InfoFile.Info
  description: Basic information of the file
  type: string
- contextPath: File.Extension
  description: The extension of the file
  type: string
- contextPath: InfoFile
  description: The report file's object
  type: unknown
- contextPath: WildFire.Report
  description: The submission object
  type: unknown
- contextPath: WildFire.Report.Status
  description: The status of the submission
  type: string
- contextPath: WildFire.Report.SHA256
  description: SHA256 of the submission
  type: string
- contextPath: WildFire.Report.MD5
  description: MD5 of the submission
  type: string
- contextPath: WildFire.Report.FileType
  description: The type of the submission
  type: string
- contextPath: WildFire.Report.Size
  description: The size of the submission
  type: number
- contextPath: Joe.Analysis
  description: Thee Analysis object
  type: unknown
- contextPath: Cuckoo.Task.Category
  description: Category of task
- contextPath: Cuckoo.Task.Machine
  description: Machine of task
- contextPath: Cuckoo.Task.Errors
  description: Errors of task
- contextPath: Cuckoo.Task.Target
  description: Target of task
- contextPath: Cuckoo.Task.Package
  description: Package of task
- contextPath: Cuckoo.Task.SampleID
  description: Sample ID of task
- contextPath: Cuckoo.Task.Guest
  description: Task guest
- contextPath: Cuckoo.Task.Custom
  description: Custom values of task
- contextPath: Cuckoo.Task.Owner
  description: Task owner
- contextPath: Cuckoo.Task.Priority
  description: Priority of task
- contextPath: Cuckoo.Task.Platform
  description: Platform of task
- contextPath: Cuckoo.Task.Options
  description: Task options
- contextPath: Cuckoo.Task.Status
  description: Task status
- contextPath: Cuckoo.Task.EnforceTimeout
  description: Is timeout of task enforced
- contextPath: Cuckoo.Task.Timeout
  description: Task timeout
- contextPath: Cuckoo.Task.Memory
  description: Task memory
- contextPath: Cuckoo.Task.Tags
  description: Task tags
- contextPath: Cuckoo.Task.ID
  description: ID of task
- contextPath: Cuckoo.Task.AddedOn
  description: Date on which the task was added
- contextPath: Cuckoo.Task.CompletedOn
  description: Date on which the task was completed
- contextPath: Cuckoo.Task.Score
  description: Reported score of the the task
- contextPath: Cuckoo.Task.Monitor
  description: Monitor of the reported task
- contextPath: SNDBOX.Analysis.ID
  description: Analysis ID
  type: string
- contextPath: SNDBOX.Analysis.SampleName
  description: Sample Data, could be a file name or URL
  type: string
- contextPath: SNDBOX.Analysis.Status
  description: Analysis Status
  type: string
- contextPath: SNDBOX.Analysis.Time
  description: Submitted Time
  type: date
- contextPath: SNDBOX.Analysis.Result
  description: Analysis Results
  type: string
- contextPath: SNDBOX.Analysis.Errors
  description: Raised errors during sampling
- contextPath: SNDBOX.Analysis.Link
  description: Analysis Link
  type: string
- contextPath: SNDBOX.Analysis.MD5
  description: MD5 of analysis sample
  type: string
- contextPath: SNDBOX.Analysis.SHA1
  description: SHA1 of analysis sample
  type: string
- contextPath: SNDBOX.Analysis.SHA256
  description: SHA256 of analysis sample
  type: string
- contextPath: SNDBOX.Analysis
  description: SNDBOX analysis
  type: unknown
- contextPath: HybridAnalysis.Submit.State
  description: The state of the process
  type: string
- contextPath: HybridAnalysis.Submit.SHA256
  description: The submission SHA256
  type: string
- contextPath: HybridAnalysis.Submit.JobID
  description: The JobID of the submission
  type: string
- contextPath: HybridAnalysis.Submit.EnvironmentID
  description: The environmentID of the submission
  type: string
- contextPath: HybridAnalysis.Submit
  description: The HybridAnalysis object
  type: unknown
- contextPath: ANYRUN.Task.AnalysisDate
  description: Date and time the analysis was executed.
  type: String
- contextPath: ANYRUN.Task.Behavior.Category
  description: Category of a process behavior.
  type: String
- contextPath: ANYRUN.Task.Behavior.Action
  description: Actions performed by a process.
  type: String
- contextPath: ANYRUN.Task.Behavior.ThreatLevel
  description: Threat score associated with a process behavior.
  type: Number
- contextPath: ANYRUN.Task.Behavior.ProcessUUID
  description: Unique ID of the process whose behaviors are being profiled.
  type: String
- contextPath: ANYRUN.Task.Connection.Reputation
  description: Connection reputation.
  type: String
- contextPath: ANYRUN.Task.Connection.ProcessUUID
  description: ID of the process that created the connection.
  type: String
- contextPath: ANYRUN.Task.Connection.ASN
  description: Connection autonomous system network.
  type: String
- contextPath: ANYRUN.Task.Connection.Country
  description: Connection country.
  type: String
- contextPath: ANYRUN.Task.Connection.Protocol
  description: Connection protocol.
  type: String
- contextPath: ANYRUN.Task.Connection.Port
  description: Connection port number.
  type: Number
- contextPath: ANYRUN.Task.Connection.IP
  description: Connection IP number.
  type: String
- contextPath: ANYRUN.Task.DnsRequest.Reputation
  description: Reputation of the DNS request.
  type: String
- contextPath: ANYRUN.Task.DnsRequest.IP
  description: IP addresses associated with a DNS request.
  type: Unknown
- contextPath: ANYRUN.Task.DnsRequest.Domain
  description: Domain resolution of a DNS request.
  type: String
- contextPath: ANYRUN.Task.Threat.ProcessUUID
  description: Unique process ID from where the threat originated.
  type: String
- contextPath: ANYRUN.Task.Threat.Msg
  description: Threat message.
  type: String
- contextPath: ANYRUN.Task.Threat.Class
  description: Class of the threat.
  type: String
- contextPath: ANYRUN.Task.Threat.SrcPort
  description: Port on which the threat originated.
  type: Number
- contextPath: ANYRUN.Task.Threat.DstPort
  description: Destination port of the threat.
  type: Number
- contextPath: ANYRUN.Task.Threat.SrcIP
  description: Source IP address where the threat originated.
  type: String
- contextPath: ANYRUN.Task.Threat.DstIP
  description: Destination IP address of the threat.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.Reputation
  description: Reputation of the HTTP request.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.Country
  description: HTTP request country.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.ProcessUUID
  description: ID of the process making the HTTP request.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.Body
  description: HTTP request body parameters and details.
  type: Unknown
- contextPath: ANYRUN.Task.HttpRequest.HttpCode
  description: HTTP request response code.
  type: Number
- contextPath: ANYRUN.Task.HttpRequest.Status
  description: Status of the HTTP request.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.ProxyDetected
  description: Whether the HTTP request was made through a proxy.
  type: Boolean
- contextPath: ANYRUN.Task.HttpRequest.Port
  description: HTTP request port.
  type: Number
- contextPath: ANYRUN.Task.HttpRequest.IP
  description: HTTP request IP address.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.URL
  description: HTTP request URL.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.Host
  description: HTTP request host.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.Method
  description: HTTP request method type.
  type: String
- contextPath: ANYRUN.Task.FileInfo
  description: Details of the submitted file.
  type: String
- contextPath: ANYRUN.Task.OS
  description: OS of the sandbox in which the file was analyzed.
  type: String
- contextPath: ANYRUN.Task.ID
  description: The unique ID of the task.
  type: String
- contextPath: ANYRUN.Task.MIME
  description: The MIME of the file submitted for analysis.
  type: String
- contextPath: ANYRUN.Task.MD5
  description: The MD5 hash of the file submitted for analysis.
  type: String
- contextPath: ANYRUN.Task.SHA1
  description: The SHA1 hash of the file submitted for analysis.
  type: String
- contextPath: ANYRUN.Task.SHA256
  description: The SHA256 hash of the file submitted for analysis.
  type: String
- contextPath: ANYRUN.Task.SSDeep
  description: SSDeep hash of the file submitted for analysis.
  type: String
- contextPath: ANYRUN.Task.Verdict
  description: ANY.RUN verdict for the maliciousness of the submitted file or URL.
  type: String
- contextPath: ANYRUN.Task.Process.FileName
  description: File name of the process.
  type: String
- contextPath: ANYRUN.Task.Process.PID
  description: Process identification number.
  type: Number
- contextPath: ANYRUN.Task.Process.PPID
  description: Parent process identification number.
  type: Number
- contextPath: ANYRUN.Task.Process.ProcessUUID
  description: Unique process ID (used by ANY.RUN).
  type: String
- contextPath: ANYRUN.Task.Process.CMD
  description: Process command.
  type: String
- contextPath: ANYRUN.Task.Process.Path
  description: Path of the executed command.
  type: String
- contextPath: ANYRUN.Task.Process.User
  description: User who executed the command.
  type: String
- contextPath: ANYRUN.Task.Process.IntegrityLevel
  description: The process integrity level.
  type: String
- contextPath: ANYRUN.Task.Process.ExitCode
  description: Process exit code.
  type: Number
- contextPath: ANYRUN.Task.Process.MainProcess
  description: Whether the process is the main process.
  type: Boolean
- contextPath: ANYRUN.Task.Process.Version.Company
  description: Company responsible for the program executed.
  type: String
- contextPath: ANYRUN.Task.Process.Version.Description
  description: Description of the type of program.
  type: String
- contextPath: ANYRUN.Task.Process.Version.Version
  description: Version of the program executed.
  type: String
- contextPath: File.SSDeep
  description: SSDeep hash of the file submitted for analysis.
  type: String
- contextPath: ANYRUN.Task.Status
  description: Task analysis status.
  type: String
sourceplaybookid: Detonate File - Generic
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Playbook start point
      id: 454650df-c42f-4915-84cf-9a908e1bff04
      iscommand: false
      name: ""
      version: -1
    taskid: 454650df-c42f-4915-84cf-9a908e1bff04
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Done
      id: 2a8f5bbb-7692-4ece-8abe-9801c7b05c3c
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2a8f5bbb-7692-4ece-8abe-9801c7b05c3c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "23":
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: c9c0d1c0-1377-4f05-847c-b70d1106a6a2
      iscommand: false
      name: Detonate File - HybridAnalysis_copy
      playbookId: 5260332f-e1e0-48b2-8026-c8ae19c7bd12
      type: playbook
      version: -1
    taskid: c9c0d1c0-1377-4f05-847c-b70d1106a6a2
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "25":
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      File:
        complex:
          root: File
      Interval:
        simple: "1"
      Timeout:
        simple: "15"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 5feda218-6556-4c59-81a3-1e1a76f6b109
      iscommand: false
      name: WildFire - Detonate file_copy
      playbookId: 9d98169e-f753-48e5-87be-f8afa0bb9181
      type: playbook
      version: -1
    taskid: 5feda218-6556-4c59-81a3-1e1a76f6b109
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 510,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 840,
        "x": 50,
        "y": 50
      }
    }
  }
